/*
 * This file is generated by jOOQ.
 */
package name.martingeisse.miner.server.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import name.martingeisse.miner.server.jooq.Indexes;
import name.martingeisse.miner.server.jooq.Keys;
import name.martingeisse.miner.server.jooq.minerTable;
import name.martingeisse.miner.server.jooq.tables.PlayerTable.PlayerJooqPath;
import name.martingeisse.miner.server.jooq.tables.records.PlayerAwardedAchievementRow;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PlayerAwardedAchievementTable extends TableImpl<PlayerAwardedAchievementRow> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>miner.PlayerAwardedAchievement</code>
     */
    public static final PlayerAwardedAchievementTable playerAwardedAchievement = new PlayerAwardedAchievementTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PlayerAwardedAchievementRow> getRecordType() {
        return PlayerAwardedAchievementRow.class;
    }

    /**
     * The column <code>miner.PlayerAwardedAchievement.id</code>.
     */
    public final TableField<PlayerAwardedAchievementRow, Long> id = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("nextval('miner.\"PlayerAwardedAchievement_id_seq\"'::regclass)"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>miner.PlayerAwardedAchievement.playerId</code>.
     */
    public final TableField<PlayerAwardedAchievementRow, Long> playerId = createField(DSL.name("playerId"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>miner.PlayerAwardedAchievement.achievementCode</code>.
     */
    public final TableField<PlayerAwardedAchievementRow, String> achievementCode = createField(DSL.name("achievementCode"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private PlayerAwardedAchievementTable(Name alias, Table<PlayerAwardedAchievementRow> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PlayerAwardedAchievementTable(Name alias, Table<PlayerAwardedAchievementRow> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>miner.PlayerAwardedAchievement</code> table
     * reference
     */
    public PlayerAwardedAchievementTable(String alias) {
        this(DSL.name(alias), playerAwardedAchievement);
    }

    /**
     * Create an aliased <code>miner.PlayerAwardedAchievement</code> table
     * reference
     */
    public PlayerAwardedAchievementTable(Name alias) {
        this(alias, playerAwardedAchievement);
    }

    /**
     * Create a <code>miner.PlayerAwardedAchievement</code> table reference
     */
    public PlayerAwardedAchievementTable() {
        this(DSL.name("PlayerAwardedAchievement"), null);
    }

    public <O extends Record> PlayerAwardedAchievementTable(Table<O> path, ForeignKey<O, PlayerAwardedAchievementRow> childPath, InverseForeignKey<O, PlayerAwardedAchievementRow> parentPath) {
        super(path, childPath, parentPath, playerAwardedAchievement);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class PlayerAwardedAchievementJooqPath extends PlayerAwardedAchievementTable implements Path<PlayerAwardedAchievementRow> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PlayerAwardedAchievementJooqPath(Table<O> path, ForeignKey<O, PlayerAwardedAchievementRow> childPath, InverseForeignKey<O, PlayerAwardedAchievementRow> parentPath) {
            super(path, childPath, parentPath);
        }
        private PlayerAwardedAchievementJooqPath(Name alias, Table<PlayerAwardedAchievementRow> aliased) {
            super(alias, aliased);
        }

        @Override
        public PlayerAwardedAchievementJooqPath as(String alias) {
            return new PlayerAwardedAchievementJooqPath(DSL.name(alias), this);
        }

        @Override
        public PlayerAwardedAchievementJooqPath as(Name alias) {
            return new PlayerAwardedAchievementJooqPath(alias, this);
        }

        @Override
        public PlayerAwardedAchievementJooqPath as(Table<?> alias) {
            return new PlayerAwardedAchievementJooqPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : minerTable.miner;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.playerAwardedAchievement_main);
    }

    @Override
    public UniqueKey<PlayerAwardedAchievementRow> getPrimaryKey() {
        return Keys.playerAwardedAchievement_pkey;
    }

    @Override
    public List<ForeignKey<PlayerAwardedAchievementRow, ?>> getReferences() {
        return Arrays.asList(Keys.playerAwardedAchievement_playerId_fkey);
    }

    private transient PlayerJooqPath _callPlayerAwardedAchievement_playerId_fkey;

    /**
     * Get the implicit join path to the <code>miner.Player</code> table.
     */
    public PlayerJooqPath callPlayerAwardedAchievement_playerId_fkey() {
        if (_callPlayerAwardedAchievement_playerId_fkey == null)
            _callPlayerAwardedAchievement_playerId_fkey = new PlayerJooqPath(this, Keys.playerAwardedAchievement_playerId_fkey, null);

        return _callPlayerAwardedAchievement_playerId_fkey;
    }

    @Override
    public PlayerAwardedAchievementTable as(String alias) {
        return new PlayerAwardedAchievementTable(DSL.name(alias), this);
    }

    @Override
    public PlayerAwardedAchievementTable as(Name alias) {
        return new PlayerAwardedAchievementTable(alias, this);
    }

    @Override
    public PlayerAwardedAchievementTable as(Table<?> alias) {
        return new PlayerAwardedAchievementTable(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PlayerAwardedAchievementTable rename(String name) {
        return new PlayerAwardedAchievementTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PlayerAwardedAchievementTable rename(Name name) {
        return new PlayerAwardedAchievementTable(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PlayerAwardedAchievementTable rename(Table<?> name) {
        return new PlayerAwardedAchievementTable(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlayerAwardedAchievementTable where(Condition condition) {
        return new PlayerAwardedAchievementTable(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlayerAwardedAchievementTable where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlayerAwardedAchievementTable where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlayerAwardedAchievementTable where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlayerAwardedAchievementTable where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlayerAwardedAchievementTable where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlayerAwardedAchievementTable where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlayerAwardedAchievementTable where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlayerAwardedAchievementTable whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlayerAwardedAchievementTable whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
