/*
 * This file is generated by jOOQ.
 */
package name.martingeisse.miner.server.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import name.martingeisse.miner.server.jooq.Indexes;
import name.martingeisse.miner.server.jooq.Keys;
import name.martingeisse.miner.server.jooq.minerTable;
import name.martingeisse.miner.server.jooq.tables.PlayerTable.PlayerJooqPath;
import name.martingeisse.miner.server.jooq.tables.records.PlayerInventorySlotRow;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PlayerInventorySlotTable extends TableImpl<PlayerInventorySlotRow> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>miner.PlayerInventorySlot</code>
     */
    public static final PlayerInventorySlotTable playerInventorySlot = new PlayerInventorySlotTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PlayerInventorySlotRow> getRecordType() {
        return PlayerInventorySlotRow.class;
    }

    /**
     * The column <code>miner.PlayerInventorySlot.id</code>.
     */
    public final TableField<PlayerInventorySlotRow, Long> id = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("nextval('miner.\"PlayerInventorySlot_id_seq\"'::regclass)"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>miner.PlayerInventorySlot.playerId</code>.
     */
    public final TableField<PlayerInventorySlotRow, Long> playerId = createField(DSL.name("playerId"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>miner.PlayerInventorySlot.type</code>.
     */
    public final TableField<PlayerInventorySlotRow, Integer> type = createField(DSL.name("type"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>miner.PlayerInventorySlot.quantity</code>.
     */
    public final TableField<PlayerInventorySlotRow, Integer> quantity = createField(DSL.name("quantity"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>miner.PlayerInventorySlot.equipped</code>.
     */
    public final TableField<PlayerInventorySlotRow, Boolean> equipped = createField(DSL.name("equipped"), SQLDataType.BOOLEAN.nullable(false), this, "");

    private PlayerInventorySlotTable(Name alias, Table<PlayerInventorySlotRow> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PlayerInventorySlotTable(Name alias, Table<PlayerInventorySlotRow> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>miner.PlayerInventorySlot</code> table reference
     */
    public PlayerInventorySlotTable(String alias) {
        this(DSL.name(alias), playerInventorySlot);
    }

    /**
     * Create an aliased <code>miner.PlayerInventorySlot</code> table reference
     */
    public PlayerInventorySlotTable(Name alias) {
        this(alias, playerInventorySlot);
    }

    /**
     * Create a <code>miner.PlayerInventorySlot</code> table reference
     */
    public PlayerInventorySlotTable() {
        this(DSL.name("PlayerInventorySlot"), null);
    }

    public <O extends Record> PlayerInventorySlotTable(Table<O> path, ForeignKey<O, PlayerInventorySlotRow> childPath, InverseForeignKey<O, PlayerInventorySlotRow> parentPath) {
        super(path, childPath, parentPath, playerInventorySlot);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class PlayerInventorySlotJooqPath extends PlayerInventorySlotTable implements Path<PlayerInventorySlotRow> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PlayerInventorySlotJooqPath(Table<O> path, ForeignKey<O, PlayerInventorySlotRow> childPath, InverseForeignKey<O, PlayerInventorySlotRow> parentPath) {
            super(path, childPath, parentPath);
        }
        private PlayerInventorySlotJooqPath(Name alias, Table<PlayerInventorySlotRow> aliased) {
            super(alias, aliased);
        }

        @Override
        public PlayerInventorySlotJooqPath as(String alias) {
            return new PlayerInventorySlotJooqPath(DSL.name(alias), this);
        }

        @Override
        public PlayerInventorySlotJooqPath as(Name alias) {
            return new PlayerInventorySlotJooqPath(alias, this);
        }

        @Override
        public PlayerInventorySlotJooqPath as(Table<?> alias) {
            return new PlayerInventorySlotJooqPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : minerTable.miner;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.playerInventorySlot_main);
    }

    @Override
    public UniqueKey<PlayerInventorySlotRow> getPrimaryKey() {
        return Keys.playerInventorySlot_pkey;
    }

    @Override
    public List<ForeignKey<PlayerInventorySlotRow, ?>> getReferences() {
        return Arrays.asList(Keys.playerInventorySlot_playerId_fkey);
    }

    private transient PlayerJooqPath _callPlayerInventorySlot_playerId_fkey;

    /**
     * Get the implicit join path to the <code>miner.Player</code> table.
     */
    public PlayerJooqPath callPlayerInventorySlot_playerId_fkey() {
        if (_callPlayerInventorySlot_playerId_fkey == null)
            _callPlayerInventorySlot_playerId_fkey = new PlayerJooqPath(this, Keys.playerInventorySlot_playerId_fkey, null);

        return _callPlayerInventorySlot_playerId_fkey;
    }

    @Override
    public List<Check<PlayerInventorySlotRow>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("PlayerInventorySlot_quantity_check"), "((quantity > 0))", true)
        );
    }

    @Override
    public PlayerInventorySlotTable as(String alias) {
        return new PlayerInventorySlotTable(DSL.name(alias), this);
    }

    @Override
    public PlayerInventorySlotTable as(Name alias) {
        return new PlayerInventorySlotTable(alias, this);
    }

    @Override
    public PlayerInventorySlotTable as(Table<?> alias) {
        return new PlayerInventorySlotTable(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PlayerInventorySlotTable rename(String name) {
        return new PlayerInventorySlotTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PlayerInventorySlotTable rename(Name name) {
        return new PlayerInventorySlotTable(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PlayerInventorySlotTable rename(Table<?> name) {
        return new PlayerInventorySlotTable(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlayerInventorySlotTable where(Condition condition) {
        return new PlayerInventorySlotTable(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlayerInventorySlotTable where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlayerInventorySlotTable where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlayerInventorySlotTable where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlayerInventorySlotTable where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlayerInventorySlotTable where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlayerInventorySlotTable where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlayerInventorySlotTable where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlayerInventorySlotTable whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlayerInventorySlotTable whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
