/*
 * This file is generated by jOOQ.
 */
package name.martingeisse.miner.server.jooq.tables;


import java.math.BigDecimal;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import name.martingeisse.miner.server.jooq.Keys;
import name.martingeisse.miner.server.jooq.minerTable;
import name.martingeisse.miner.server.jooq.tables.PlayerAwardedAchievementTable.PlayerAwardedAchievementJooqPath;
import name.martingeisse.miner.server.jooq.tables.PlayerInventorySlotTable.PlayerInventorySlotJooqPath;
import name.martingeisse.miner.server.jooq.tables.UserAccountTable.UserAccountJooqPath;
import name.martingeisse.miner.server.jooq.tables.records.PlayerRow;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PlayerTable extends TableImpl<PlayerRow> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>miner.Player</code>
     */
    public static final PlayerTable player = new PlayerTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PlayerRow> getRecordType() {
        return PlayerRow.class;
    }

    /**
     * The column <code>miner.Player.id</code>.
     */
    public final TableField<PlayerRow, Long> id = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("nextval('miner.\"Player_id_seq\"'::regclass)"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>miner.Player.userAccountId</code>.
     */
    public final TableField<PlayerRow, Long> userAccountId = createField(DSL.name("userAccountId"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>miner.Player.name</code>.
     */
    public final TableField<PlayerRow, String> name_ = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>miner.Player.faction</code>.
     */
    public final TableField<PlayerRow, Integer> faction = createField(DSL.name("faction"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>miner.Player.x</code>.
     */
    public final TableField<PlayerRow, BigDecimal> x = createField(DSL.name("x"), SQLDataType.NUMERIC(10, 2).nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.NUMERIC)), this, "");

    /**
     * The column <code>miner.Player.y</code>.
     */
    public final TableField<PlayerRow, BigDecimal> y = createField(DSL.name("y"), SQLDataType.NUMERIC(10, 2).nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.NUMERIC)), this, "");

    /**
     * The column <code>miner.Player.z</code>.
     */
    public final TableField<PlayerRow, BigDecimal> z = createField(DSL.name("z"), SQLDataType.NUMERIC(10, 2).nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.NUMERIC)), this, "");

    /**
     * The column <code>miner.Player.leftAngle</code>.
     */
    public final TableField<PlayerRow, BigDecimal> leftAngle = createField(DSL.name("leftAngle"), SQLDataType.NUMERIC(5, 2).nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.NUMERIC)), this, "");

    /**
     * The column <code>miner.Player.upAngle</code>.
     */
    public final TableField<PlayerRow, BigDecimal> upAngle = createField(DSL.name("upAngle"), SQLDataType.NUMERIC(5, 2).nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.NUMERIC)), this, "");

    /**
     * The column <code>miner.Player.coins</code>.
     */
    public final TableField<PlayerRow, Long> coins = createField(DSL.name("coins"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>miner.Player.deleted</code>.
     */
    public final TableField<PlayerRow, Boolean> deleted = createField(DSL.name("deleted"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    private PlayerTable(Name alias, Table<PlayerRow> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PlayerTable(Name alias, Table<PlayerRow> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>miner.Player</code> table reference
     */
    public PlayerTable(String alias) {
        this(DSL.name(alias), player);
    }

    /**
     * Create an aliased <code>miner.Player</code> table reference
     */
    public PlayerTable(Name alias) {
        this(alias, player);
    }

    /**
     * Create a <code>miner.Player</code> table reference
     */
    public PlayerTable() {
        this(DSL.name("Player"), null);
    }

    public <O extends Record> PlayerTable(Table<O> path, ForeignKey<O, PlayerRow> childPath, InverseForeignKey<O, PlayerRow> parentPath) {
        super(path, childPath, parentPath, player);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class PlayerJooqPath extends PlayerTable implements Path<PlayerRow> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PlayerJooqPath(Table<O> path, ForeignKey<O, PlayerRow> childPath, InverseForeignKey<O, PlayerRow> parentPath) {
            super(path, childPath, parentPath);
        }
        private PlayerJooqPath(Name alias, Table<PlayerRow> aliased) {
            super(alias, aliased);
        }

        @Override
        public PlayerJooqPath as(String alias) {
            return new PlayerJooqPath(DSL.name(alias), this);
        }

        @Override
        public PlayerJooqPath as(Name alias) {
            return new PlayerJooqPath(alias, this);
        }

        @Override
        public PlayerJooqPath as(Table<?> alias) {
            return new PlayerJooqPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : minerTable.miner;
    }

    @Override
    public UniqueKey<PlayerRow> getPrimaryKey() {
        return Keys.player_pkey;
    }

    @Override
    public List<ForeignKey<PlayerRow, ?>> getReferences() {
        return Arrays.asList(Keys.player_userAccountId_fkey);
    }

    private transient UserAccountJooqPath _callPlayer_userAccountId_fkey;

    /**
     * Get the implicit join path to the <code>miner.UserAccount</code> table.
     */
    public UserAccountJooqPath callPlayer_userAccountId_fkey() {
        if (_callPlayer_userAccountId_fkey == null)
            _callPlayer_userAccountId_fkey = new UserAccountJooqPath(this, Keys.player_userAccountId_fkey, null);

        return _callPlayer_userAccountId_fkey;
    }

    private transient PlayerAwardedAchievementJooqPath _callPlayerAwardedAchievement_playerId_fkey;

    /**
     * Get the implicit to-many join path to the
     * <code>miner.PlayerAwardedAchievement</code> table
     */
    public PlayerAwardedAchievementJooqPath callPlayerAwardedAchievement_playerId_fkey() {
        if (_callPlayerAwardedAchievement_playerId_fkey == null)
            _callPlayerAwardedAchievement_playerId_fkey = new PlayerAwardedAchievementJooqPath(this, null, Keys.playerAwardedAchievement_playerId_fkey.getInverseKey());

        return _callPlayerAwardedAchievement_playerId_fkey;
    }

    private transient PlayerInventorySlotJooqPath _callPlayerInventorySlot_playerId_fkey;

    /**
     * Get the implicit to-many join path to the
     * <code>miner.PlayerInventorySlot</code> table
     */
    public PlayerInventorySlotJooqPath callPlayerInventorySlot_playerId_fkey() {
        if (_callPlayerInventorySlot_playerId_fkey == null)
            _callPlayerInventorySlot_playerId_fkey = new PlayerInventorySlotJooqPath(this, null, Keys.playerInventorySlot_playerId_fkey.getInverseKey());

        return _callPlayerInventorySlot_playerId_fkey;
    }

    @Override
    public List<Check<PlayerRow>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("Player_coins_check"), "((coins >= 0))", true),
            Internal.createCheck(this, DSL.name("Player_faction_check"), "(((faction >= 0) AND (faction < 4)))", true)
        );
    }

    @Override
    public PlayerTable as(String alias) {
        return new PlayerTable(DSL.name(alias), this);
    }

    @Override
    public PlayerTable as(Name alias) {
        return new PlayerTable(alias, this);
    }

    @Override
    public PlayerTable as(Table<?> alias) {
        return new PlayerTable(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PlayerTable rename(String name) {
        return new PlayerTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PlayerTable rename(Name name) {
        return new PlayerTable(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PlayerTable rename(Table<?> name) {
        return new PlayerTable(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlayerTable where(Condition condition) {
        return new PlayerTable(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlayerTable where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlayerTable where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlayerTable where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlayerTable where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlayerTable where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlayerTable where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlayerTable where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlayerTable whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlayerTable whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
