/*
 * This file is generated by jOOQ.
 */
package name.martingeisse.miner.server.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import name.martingeisse.miner.server.jooq.Keys;
import name.martingeisse.miner.server.jooq.minerTable;
import name.martingeisse.miner.server.jooq.tables.PlayerTable.PlayerJooqPath;
import name.martingeisse.miner.server.jooq.tables.records.UserAccountRow;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserAccountTable extends TableImpl<UserAccountRow> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>miner.UserAccount</code>
     */
    public static final UserAccountTable userAccount = new UserAccountTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserAccountRow> getRecordType() {
        return UserAccountRow.class;
    }

    /**
     * The column <code>miner.UserAccount.id</code>.
     */
    public final TableField<UserAccountRow, Long> id = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("nextval('miner.\"UserAccount_id_seq\"'::regclass)"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>miner.UserAccount.username</code>.
     */
    public final TableField<UserAccountRow, String> username = createField(DSL.name("username"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>miner.UserAccount.passwordHash</code>.
     */
    public final TableField<UserAccountRow, byte[]> passwordHash = createField(DSL.name("passwordHash"), SQLDataType.BLOB.nullable(false), this, "");

    /**
     * The column <code>miner.UserAccount.deleted</code>.
     */
    public final TableField<UserAccountRow, Boolean> deleted = createField(DSL.name("deleted"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    private UserAccountTable(Name alias, Table<UserAccountRow> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private UserAccountTable(Name alias, Table<UserAccountRow> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>miner.UserAccount</code> table reference
     */
    public UserAccountTable(String alias) {
        this(DSL.name(alias), userAccount);
    }

    /**
     * Create an aliased <code>miner.UserAccount</code> table reference
     */
    public UserAccountTable(Name alias) {
        this(alias, userAccount);
    }

    /**
     * Create a <code>miner.UserAccount</code> table reference
     */
    public UserAccountTable() {
        this(DSL.name("UserAccount"), null);
    }

    public <O extends Record> UserAccountTable(Table<O> path, ForeignKey<O, UserAccountRow> childPath, InverseForeignKey<O, UserAccountRow> parentPath) {
        super(path, childPath, parentPath, userAccount);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class UserAccountJooqPath extends UserAccountTable implements Path<UserAccountRow> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> UserAccountJooqPath(Table<O> path, ForeignKey<O, UserAccountRow> childPath, InverseForeignKey<O, UserAccountRow> parentPath) {
            super(path, childPath, parentPath);
        }
        private UserAccountJooqPath(Name alias, Table<UserAccountRow> aliased) {
            super(alias, aliased);
        }

        @Override
        public UserAccountJooqPath as(String alias) {
            return new UserAccountJooqPath(DSL.name(alias), this);
        }

        @Override
        public UserAccountJooqPath as(Name alias) {
            return new UserAccountJooqPath(alias, this);
        }

        @Override
        public UserAccountJooqPath as(Table<?> alias) {
            return new UserAccountJooqPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : minerTable.miner;
    }

    @Override
    public UniqueKey<UserAccountRow> getPrimaryKey() {
        return Keys.userAccount_pkey;
    }

    private transient PlayerJooqPath _callPlayer_userAccountId_fkey;

    /**
     * Get the implicit to-many join path to the <code>miner.Player</code> table
     */
    public PlayerJooqPath callPlayer_userAccountId_fkey() {
        if (_callPlayer_userAccountId_fkey == null)
            _callPlayer_userAccountId_fkey = new PlayerJooqPath(this, null, Keys.player_userAccountId_fkey.getInverseKey());

        return _callPlayer_userAccountId_fkey;
    }

    @Override
    public List<Check<UserAccountRow>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("UserAccount_username_check"), "(((username)::text <> ''::text))", true)
        );
    }

    @Override
    public UserAccountTable as(String alias) {
        return new UserAccountTable(DSL.name(alias), this);
    }

    @Override
    public UserAccountTable as(Name alias) {
        return new UserAccountTable(alias, this);
    }

    @Override
    public UserAccountTable as(Table<?> alias) {
        return new UserAccountTable(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserAccountTable rename(String name) {
        return new UserAccountTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserAccountTable rename(Name name) {
        return new UserAccountTable(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserAccountTable rename(Table<?> name) {
        return new UserAccountTable(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserAccountTable where(Condition condition) {
        return new UserAccountTable(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserAccountTable where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserAccountTable where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserAccountTable where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserAccountTable where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserAccountTable where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserAccountTable where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserAccountTable where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserAccountTable whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserAccountTable whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
