/*
 * This file is generated by jOOQ.
 */
package name.martingeisse.miner.server.jooq.tables.records;


import name.martingeisse.miner.server.jooq.tables.PlayerAwardedAchievementTable;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PlayerAwardedAchievementRow extends UpdatableRecordImpl<PlayerAwardedAchievementRow> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>miner.PlayerAwardedAchievement.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>miner.PlayerAwardedAchievement.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>miner.PlayerAwardedAchievement.playerId</code>.
     */
    public void setPlayerId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>miner.PlayerAwardedAchievement.playerId</code>.
     */
    public Long getPlayerId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>miner.PlayerAwardedAchievement.achievementCode</code>.
     */
    public void setAchievementCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>miner.PlayerAwardedAchievement.achievementCode</code>.
     */
    public String getAchievementCode() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PlayerAwardedAchievementRow
     */
    public PlayerAwardedAchievementRow() {
        super(PlayerAwardedAchievementTable.playerAwardedAchievement);
    }

    /**
     * Create a detached, initialised PlayerAwardedAchievementRow
     */
    public PlayerAwardedAchievementRow(Long id, Long playerId, String achievementCode) {
        super(PlayerAwardedAchievementTable.playerAwardedAchievement);

        setId(id);
        setPlayerId(playerId);
        setAchievementCode(achievementCode);
        resetChangedOnNotNull();
    }
}
