/*
 * This file is generated by jOOQ.
 */
package name.martingeisse.miner.server.jooq.tables.records;


import name.martingeisse.miner.server.jooq.tables.PlayerInventorySlotTable;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PlayerInventorySlotRow extends UpdatableRecordImpl<PlayerInventorySlotRow> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>miner.PlayerInventorySlot.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>miner.PlayerInventorySlot.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>miner.PlayerInventorySlot.playerId</code>.
     */
    public void setPlayerId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>miner.PlayerInventorySlot.playerId</code>.
     */
    public Long getPlayerId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>miner.PlayerInventorySlot.type</code>.
     */
    public void setType(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>miner.PlayerInventorySlot.type</code>.
     */
    public Integer getType() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>miner.PlayerInventorySlot.quantity</code>.
     */
    public void setQuantity(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>miner.PlayerInventorySlot.quantity</code>.
     */
    public Integer getQuantity() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>miner.PlayerInventorySlot.equipped</code>.
     */
    public void setEquipped(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>miner.PlayerInventorySlot.equipped</code>.
     */
    public Boolean getEquipped() {
        return (Boolean) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PlayerInventorySlotRow
     */
    public PlayerInventorySlotRow() {
        super(PlayerInventorySlotTable.playerInventorySlot);
    }

    /**
     * Create a detached, initialised PlayerInventorySlotRow
     */
    public PlayerInventorySlotRow(Long id, Long playerId, Integer type, Integer quantity, Boolean equipped) {
        super(PlayerInventorySlotTable.playerInventorySlot);

        setId(id);
        setPlayerId(playerId);
        setType(type);
        setQuantity(quantity);
        setEquipped(equipped);
        resetChangedOnNotNull();
    }
}
