/*
 * This file is generated by jOOQ.
 */
package name.martingeisse.miner.server.jooq.tables.records;


import java.math.BigDecimal;

import name.martingeisse.miner.server.jooq.tables.PlayerTable;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PlayerRow extends UpdatableRecordImpl<PlayerRow> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>miner.Player.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>miner.Player.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>miner.Player.userAccountId</code>.
     */
    public void setUserAccountId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>miner.Player.userAccountId</code>.
     */
    public Long getUserAccountId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>miner.Player.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>miner.Player.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>miner.Player.faction</code>.
     */
    public void setFaction(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>miner.Player.faction</code>.
     */
    public Integer getFaction() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>miner.Player.x</code>.
     */
    public void setX(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>miner.Player.x</code>.
     */
    public BigDecimal getX() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>miner.Player.y</code>.
     */
    public void setY(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>miner.Player.y</code>.
     */
    public BigDecimal getY() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>miner.Player.z</code>.
     */
    public void setZ(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>miner.Player.z</code>.
     */
    public BigDecimal getZ() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>miner.Player.leftAngle</code>.
     */
    public void setLeftAngle(BigDecimal value) {
        set(7, value);
    }

    /**
     * Getter for <code>miner.Player.leftAngle</code>.
     */
    public BigDecimal getLeftAngle() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>miner.Player.upAngle</code>.
     */
    public void setUpAngle(BigDecimal value) {
        set(8, value);
    }

    /**
     * Getter for <code>miner.Player.upAngle</code>.
     */
    public BigDecimal getUpAngle() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>miner.Player.coins</code>.
     */
    public void setCoins(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>miner.Player.coins</code>.
     */
    public Long getCoins() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>miner.Player.deleted</code>.
     */
    public void setDeleted(Boolean value) {
        set(10, value);
    }

    /**
     * Getter for <code>miner.Player.deleted</code>.
     */
    public Boolean getDeleted() {
        return (Boolean) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PlayerRow
     */
    public PlayerRow() {
        super(PlayerTable.player);
    }

    /**
     * Create a detached, initialised PlayerRow
     */
    public PlayerRow(Long id, Long userAccountId, String name_, Integer faction, BigDecimal x, BigDecimal y, BigDecimal z, BigDecimal leftAngle, BigDecimal upAngle, Long coins, Boolean deleted) {
        super(PlayerTable.player);

        setId(id);
        setUserAccountId(userAccountId);
        setName(name_);
        setFaction(faction);
        setX(x);
        setY(y);
        setZ(z);
        setLeftAngle(leftAngle);
        setUpAngle(upAngle);
        setCoins(coins);
        setDeleted(deleted);
        resetChangedOnNotNull();
    }
}
