/*
 * This file is generated by jOOQ.
 */
package name.martingeisse.miner.server.jooq.tables.records;


import name.martingeisse.miner.server.jooq.tables.UserAccountTable;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserAccountRow extends UpdatableRecordImpl<UserAccountRow> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>miner.UserAccount.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>miner.UserAccount.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>miner.UserAccount.username</code>.
     */
    public void setUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>miner.UserAccount.username</code>.
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>miner.UserAccount.passwordHash</code>.
     */
    public void setPasswordHash(byte[] value) {
        set(2, value);
    }

    /**
     * Getter for <code>miner.UserAccount.passwordHash</code>.
     */
    public byte[] getPasswordHash() {
        return (byte[]) get(2);
    }

    /**
     * Setter for <code>miner.UserAccount.deleted</code>.
     */
    public void setDeleted(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>miner.UserAccount.deleted</code>.
     */
    public Boolean getDeleted() {
        return (Boolean) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserAccountRow
     */
    public UserAccountRow() {
        super(UserAccountTable.userAccount);
    }

    /**
     * Create a detached, initialised UserAccountRow
     */
    public UserAccountRow(Long id, String username, byte[] passwordHash, Boolean deleted) {
        super(UserAccountTable.userAccount);

        setId(id);
        setUsername(username);
        setPasswordHash(passwordHash);
        setDeleted(deleted);
        resetChangedOnNotNull();
    }
}
