/*
 * This file is generated by jOOQ.
 */
package name.martingeisse.miner.server.jooq;


import name.martingeisse.miner.server.jooq.tables.PlayerAwardedAchievementTable;
import name.martingeisse.miner.server.jooq.tables.PlayerInventorySlotTable;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in miner.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index playerAwardedAchievement_main = Internal.createIndex(DSL.name("PlayerAwardedAchievement_main"), PlayerAwardedAchievementTable.playerAwardedAchievement, new OrderField[] { PlayerAwardedAchievementTable.playerAwardedAchievement.playerId, PlayerAwardedAchievementTable.playerAwardedAchievement.achievementCode }, true);
    public static final Index playerInventorySlot_main = Internal.createIndex(DSL.name("PlayerInventorySlot_main"), PlayerInventorySlotTable.playerInventorySlot, new OrderField[] { PlayerInventorySlotTable.playerInventorySlot.playerId, PlayerInventorySlotTable.playerInventorySlot.id }, false);
}
