/*
 * This file is generated by jOOQ.
 */
package name.martingeisse.miner.server.jooq;


import name.martingeisse.miner.server.jooq.tables.PlayerAwardedAchievementTable;
import name.martingeisse.miner.server.jooq.tables.PlayerInventorySlotTable;
import name.martingeisse.miner.server.jooq.tables.PlayerTable;
import name.martingeisse.miner.server.jooq.tables.UserAccountTable;
import name.martingeisse.miner.server.jooq.tables.records.PlayerAwardedAchievementRow;
import name.martingeisse.miner.server.jooq.tables.records.PlayerInventorySlotRow;
import name.martingeisse.miner.server.jooq.tables.records.PlayerRow;
import name.martingeisse.miner.server.jooq.tables.records.UserAccountRow;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * miner.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<PlayerRow> player_pkey = Internal.createUniqueKey(PlayerTable.player, DSL.name("Player_pkey"), new TableField[] { PlayerTable.player.id }, true);
    public static final UniqueKey<PlayerAwardedAchievementRow> playerAwardedAchievement_pkey = Internal.createUniqueKey(PlayerAwardedAchievementTable.playerAwardedAchievement, DSL.name("PlayerAwardedAchievement_pkey"), new TableField[] { PlayerAwardedAchievementTable.playerAwardedAchievement.id }, true);
    public static final UniqueKey<PlayerInventorySlotRow> playerInventorySlot_pkey = Internal.createUniqueKey(PlayerInventorySlotTable.playerInventorySlot, DSL.name("PlayerInventorySlot_pkey"), new TableField[] { PlayerInventorySlotTable.playerInventorySlot.id }, true);
    public static final UniqueKey<UserAccountRow> userAccount_pkey = Internal.createUniqueKey(UserAccountTable.userAccount, DSL.name("UserAccount_pkey"), new TableField[] { UserAccountTable.userAccount.id }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<PlayerRow, UserAccountRow> player_userAccountId_fkey = Internal.createForeignKey(PlayerTable.player, DSL.name("Player_userAccountId_fkey"), new TableField[] { PlayerTable.player.userAccountId }, Keys.userAccount_pkey, new TableField[] { UserAccountTable.userAccount.id }, true);
    public static final ForeignKey<PlayerAwardedAchievementRow, PlayerRow> playerAwardedAchievement_playerId_fkey = Internal.createForeignKey(PlayerAwardedAchievementTable.playerAwardedAchievement, DSL.name("PlayerAwardedAchievement_playerId_fkey"), new TableField[] { PlayerAwardedAchievementTable.playerAwardedAchievement.playerId }, Keys.player_pkey, new TableField[] { PlayerTable.player.id }, true);
    public static final ForeignKey<PlayerInventorySlotRow, PlayerRow> playerInventorySlot_playerId_fkey = Internal.createForeignKey(PlayerInventorySlotTable.playerInventorySlot, DSL.name("PlayerInventorySlot_playerId_fkey"), new TableField[] { PlayerInventorySlotTable.playerInventorySlot.playerId }, Keys.player_pkey, new TableField[] { PlayerTable.player.id }, true);
}
