/*
 * This file is generated by jOOQ.
 */
package name.martingeisse.miner.server.jooq;


import java.util.Arrays;
import java.util.List;

import name.martingeisse.miner.server.jooq.tables.PlayerAwardedAchievementTable;
import name.martingeisse.miner.server.jooq.tables.PlayerInventorySlotTable;
import name.martingeisse.miner.server.jooq.tables.PlayerTable;
import name.martingeisse.miner.server.jooq.tables.UserAccountTable;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class minerTable extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>miner</code>
     */
    public static final minerTable miner = new minerTable();

    /**
     * The table <code>miner.Player</code>.
     */
    public final PlayerTable player = PlayerTable.player;

    /**
     * The table <code>miner.PlayerAwardedAchievement</code>.
     */
    public final PlayerAwardedAchievementTable playerAwardedAchievement = PlayerAwardedAchievementTable.playerAwardedAchievement;

    /**
     * The table <code>miner.PlayerInventorySlot</code>.
     */
    public final PlayerInventorySlotTable playerInventorySlot = PlayerInventorySlotTable.playerInventorySlot;

    /**
     * The table <code>miner.UserAccount</code>.
     */
    public final UserAccountTable userAccount = UserAccountTable.userAccount;

    /**
     * No further instances allowed
     */
    private minerTable() {
        super("miner", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.asList(
            Sequences.player_id_seq,
            Sequences.playerAwardedAchievement_id_seq,
            Sequences.playerInventorySlot_id_seq,
            Sequences.userAccount_id_seq
        );
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            PlayerTable.player,
            PlayerAwardedAchievementTable.playerAwardedAchievement,
            PlayerInventorySlotTable.playerInventorySlot,
            UserAccountTable.userAccount
        );
    }
}
