/*
 * This file is generated by jOOQ.
 */
package name.martingeisse.miner.server.jooq;


import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in miner.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Sequences {

    /**
     * The sequence <code>miner.Player_id_seq</code>
     */
    public static final Sequence<Long> player_id_seq = Internal.createSequence("Player_id_seq", minerTable.miner, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>miner.PlayerAwardedAchievement_id_seq</code>
     */
    public static final Sequence<Long> playerAwardedAchievement_id_seq = Internal.createSequence("PlayerAwardedAchievement_id_seq", minerTable.miner, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>miner.PlayerInventorySlot_id_seq</code>
     */
    public static final Sequence<Long> playerInventorySlot_id_seq = Internal.createSequence("PlayerInventorySlot_id_seq", minerTable.miner, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>miner.UserAccount_id_seq</code>
     */
    public static final Sequence<Long> userAccount_id_seq = Internal.createSequence("UserAccount_id_seq", minerTable.miner, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);
}
