/*
 * This file is generated by jOOQ.
 */
package name.martingeisse.miner.server.jooq;


import name.martingeisse.miner.server.jooq.tables.PlayerAwardedAchievementTable;
import name.martingeisse.miner.server.jooq.tables.PlayerInventorySlotTable;
import name.martingeisse.miner.server.jooq.tables.PlayerTable;
import name.martingeisse.miner.server.jooq.tables.UserAccountTable;


/**
 * Convenience access to all tables in miner.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>miner.Player</code>.
     */
    public static final PlayerTable player = PlayerTable.player;

    /**
     * The table <code>miner.PlayerAwardedAchievement</code>.
     */
    public static final PlayerAwardedAchievementTable playerAwardedAchievement = PlayerAwardedAchievementTable.playerAwardedAchievement;

    /**
     * The table <code>miner.PlayerInventorySlot</code>.
     */
    public static final PlayerInventorySlotTable playerInventorySlot = PlayerInventorySlotTable.playerInventorySlot;

    /**
     * The table <code>miner.UserAccount</code>.
     */
    public static final UserAccountTable userAccount = UserAccountTable.userAccount;
}
